# Generated by Django 5.1 on 2024-09-02 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('DYN', 'Dynamic with Fins (DYN)'), ('DNF', 'Dynamic No Fins (DNF)'), ('DYNB', 'Dynamic with Bi-Fins (DYNB)'), ('FIM', 'Free Immersion (FIM)'), ('CTW', 'Constant Weight (CTW)'), ('CTWB', 'Constant Weight Bi-Fins (CTWB)'), ('CNF', 'Constant Weight No Fins (CNF)')], default='DYN', max_length=4)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
